### ISSUE TITLE
sample env file

### ISSUE THREAD

**Issue by mmednik** [Metaschoolso/Mint-Elon-Must-NFT#1]
hi! i think could be helpful have an .env.sample file or something like this that can describe the internal structure expected for the .env file:

```
PRIVATE_KEY=YOUR-PRIVATE-KEY
API_URL_KEY=YOUR-ALCHEMY-APP-URL
API_KEY=YOUR-ALCHEMY-APP-KEY
```

**Comment by mmednik** [comment]
this recommendation applies all repos :)

**Comment by frizwan** [comment]
sample env file is committed. Thank you, great idea!!
